animes = ['A Lull in the Sea',
 'A Place Further Than The Universe',
 'A Silent Voice',
 'AKIRA',
 'Ace of Diamond',
 'Akatsuki no Yona',
 'Angel Beats!',
 'Aria The Natural',
 'Aria The Origination',
 'Assassination Classroom',
 'Attack on Titan',
 'Baccano!',
 'Bakemonogatari',
 'Bakuman',
 'Barakamon',
 'Beck Mongolian Chop Squad',
 'Berserk',
 'Big Windup!',
 'Black Butler',
 'Black Lagoon',
 'Bunny Drop',
 'Cardcaptor Sakura',
 'Carpcaptor Sakura',
 'Castle in the Sky',
 'Chihayafuru',
 'Clannad',
 'Code Geass',
 'Cross Game',
 'D.Gray-man',
 'DARLING in the FRANXX',
 'Daily Lives of High School Boys',
 'Darker than Black',
 'Death Note',
 'Death Parade',
 'Den-noh Coil',
 'Descending Stories Showa Genroku Rakugo Shinju',
 'Detective Conan',
 'Detroit Metal City The Animated Series',
 'Dragon Ball',
 'Dragon Ball Z',
 'Durarara',
 'Durarara!!',
 'ERASED',
 'Erin',
 'Eureka Seven',
 'FateZero',
 'Fatestay night',
 'Fighting Spirit Special',
 'From the New World',
 'Full Metal Panic',
 'Fullmetal Alchemist Brotherhood',
 'Gankutsuou The Count of Monte Cristo',
 'Ghost in the Shell',
 'Gintama',
 'Girls Last Tour',
 'Girls und Panzer',
 'Glass Mask',
 'Gosick',
 'Grave of the Fireflies',
 'Great Teacher Onizuka',
 'Gurren Lagann',
 'Haikyu!!',
 'Hajime no Ippo',
 'Hellsing Ultimate',
 'Higurashi When they cry',
 'Hikaru no Go',
 'Historys strongest disciple Kenichi',
 'Honey and Clover',
 'Hotarubi no Mori e',
 'Howls Moving Castle',
 'Hunter x Hunter',
 'Hyouka',
 'In This Corner of the World',
 'Initial D',
 'Interstella5555 The 5tory of The 5ecret 5tar 5ystem',
 'InuYasha The Final Act',
 'Jojos Bizarre Adventure',
 'Junjo Romantica',
 'KILL la KILL',
 'Kaiba',
 'Kaiji Ultimate Survivor',
 'Kamisama Hajimemashita',
 'Kamisama Hajimemashita Kamisama, Shiawase ni Naru',
 'Kamisama Kiss',
 'Katanagatari',
 'Kids on the Slope',
 'Kikis Delivery Service',
 'Kingdom',
 'Kinos Journey',
 'Kizumonogatari',
 'Kizumonogatari III Reiketsu-hen',
 'Kodocha',
 'KonoSuba',
 'Kurokos Basketball',
 'La Maison en Petits Cubes',
 'Laid-Back Camp',
 'Land of the Lustrous',
 'Legend of the Galactic Heroes',
 'Little Busters! ~Refrain~',
 'Lovely Complex',
 'Made in Abyss',
 'Magi The Kingdom of Magic',
 'Magi The Labyrinth of Magic',
 'Maid Sama!',
 'Maison Ikkoku',
 'Major',
 'Major S5',
 'Major World Series',
 'March comes in like a lion',
 'Megalo Box',
 'Millennium Actress',
 'Miss Kobayashis Dragon Maid',
 'Mob Psycho 100',
 'Mobile Suit Gundam',
 'Mononoke',
 'Monster',
 'Monthly Girls Nozaki-kun',
 'Moribito - Guardian of the Spirit',
 'Mr. Osomatsu',
 'Mushishi',
 'My Hero Academia',
 'My Neighbor Totoro',
 'My Teen Romantic Comedy',
 'My Teen Romantic Comedy SNAFU',
 'Nana',
 'Nanatsu no Taizai',
 'Naruto',
 'Natsume Yuujinchou',
 'Nausica� of the Valley of the Wind',
 'Neon Genesis Evangelion',
 'Nichijou',
 'Night Is Short, Walk on Girl',
 'Nisemonogatari',
 'No Game No Life',
 'No Game, No Life',
 'Nodame Cantabile',
 'Non Non Biyori Repeat',
 'Noragami',
 'Noragami Aragoto',
 'One Outs',
 'One Piece',
 'One Punch Man',
 'Ouran High School Host Club',
 'Owarimonogatari',
 'Parasyte',
 'Patema Inverted',
 'Perfect Blue',
 'Ping Pong the Animation',
 'Pingu in the City',
 'Planetes',
 'Princess Jellyfish',
 'Princess Mononoke',
 'Princess Tutu',
 'Psycho-Pass',
 'Puella Magi Madoka Magica',
 'Rainbow',
 'ReLife',
 'ReZero',
 'Reborn!',
 'Redline',
 'Revolutionary Girl Utena',
 'Rocky Joe 2',
 'Romeo and the Black Brothers',
 'Rurouni Kenshin',
 'SKET Dance',
 'Sain Seiya',
 'Saint Seiya',
 'Samurai Champloo',
 'Samurai X',
 'Sayonara no Asa ni Yakusoku no Hana wo Kazarou',
 'Sekai Ichi Hatsukoi',
 'Sekaiichi Hatsukoi',
 'Shelter',
 'Shirobako',
 'Shokugeki no Souma',
 'Showa Genroku Rakugo Shinju',
 'Silver Spoon',
 'Skip Beat!',
 'Slam Dunk',
 'Sound! Euphonium',
 'Space Brothers',
 'Spice and Wolf',
 'Spirited Away',
 'Star Blazers 2199',
 'Steins Gate',
 'Summer Wars',
 'Sword of the Stranger',
 'Terror in Resonance',
 'The Ancient Magus Bride',
 'The Anthem of the Heart',
 'The Boy and the Beast',
 'The Disappearance of Haruhi Suzumiya',
 'The Disastrous Life of Saiki K',
 'The Eccentric Family',
 'The Garden of Sinners',
 'The Garden of Words',
 'The Girl Who Leapt Through Time',
 'The Pet Girl of Sakurasou',
 'The Rose of Versailles',
 'The Seven Deadly Sins',
 'The Shadow that Devours the Sun',
 'The Tale of the Princess Kaguya',
 'The Tatami Galaxy',
 'The World God Only Knows',
 'Time of Eve',
 'Tokyo Godfathers',
 'Tokyo Magnitude 8.0',
 'Tomorrows Joe',
 'Toradora!',
 'Trigun',
 'Tsuabasa',
 'Tsukigakirei',
 'Tsukimonogatari',
 'Violet Evergarden',
 'Welcome to the Ballroom',
 'Welcome to the N.H.K',
 'When Marnie Was There',
 'Whisper of the Heart',
 'Wolf Children',
 'Working!!! Lord of the Takanashi',
 'Yona of the Dawn',
 'Your Lie in April',
 'Your Name',
 'Yowamushi Pedal',
 'Yu Yu Hakusho',
 'Yuri!!! On ICE',
 'Yuuki Yuuna wa Yuusha de Aru Washio Sumi no Shou 2 - Tamashii',
 'anohana The Flower We Saw That Day',
 'cowboy bebop',
 'xxxHOLiC',
 'xxxHOLiC Kei']